---
title: "ロッドの組み立て"
permalink: /make3d/assembling-the-rods/
toc: true
---
以下の部品を準備します。

- アルミフレーム(小)：６本
- カーボンロッド：６本
- ロッドエンド：１２個
- M3-8ボルト：１２個
- M3ナット：１２個

<figure>
  <img src="{{ '/assets/images/make3d/201/201-1.webp' | relative_url }}" alt="201-1">
</figure>

最初に、M3-8ボルトの先端にM3ナットを取り付けます。

<figure>
  <img src="{{ '/assets/images/make3d/201/201-2.webp' | relative_url }}" alt="201-2">
</figure>

アルミフレームの先端にボルトを入れてしっかり締めます。アルミフレームの反対側はボルトを取り付けません。

<figure>
  <img src="{{ '/assets/images/make3d/201/201-3.webp' | relative_url }}" alt="201-3">
</figure>

エポキシ樹脂をロッドエンドのネジ部分にたっぷり塗ります。

<figure>
  <img src="{{ '/assets/images/make3d/201/201-4.webp' | relative_url }}" alt="201-4">
</figure>

カーボンロッドにロッドエンドを差し込みます。この時エポキシ樹脂がはみ出しますので、キッチンペーパーなどで軽く拭き取ります。カーボンロッドの反対側も同様に行います。カーボンロッドの中に圧縮された空気がロッドエンドを押し出そうとするので、しっかりと両側を押さえます。

<figure>
  <img src="{{ '/assets/images/make3d/201/201-5.webp' | relative_url }}" alt="201-5">
</figure>

ロッドエンドを取り付けたカーボンロッドをアルミフレームの溝に沿って置きます。ロッドエンドの向きが揃うように調整します。

<figure>
  <img src="{{ '/assets/images/make3d/201/201-6.webp' | relative_url }}" alt="201-6">
</figure>

ボルトで固定していない側にボルトを差し込みます。下の図の様に、斜めになるように差し込み、ボルトを締めます。こうすることで、垂直に立とうとするボルトがロッドエンドを押さえる形となります。この押さえが緩いと、ロッド内部の空気の圧力でロッドエンドが飛び出してしまい、ロッドの長さが変わってしまいますので注意が必要です。

<figure>
  <img src="{{ '/assets/images/make3d/201/201-7.webp' | relative_url }}" alt="201-7">
</figure>

６本のロッドに対して同様に行います。十分に硬化したところで取り外します。ボルトとナットは他の部品で再利用します。

<figure>
  <img src="{{ '/assets/images/make3d/201/201-8.webp' | relative_url }}" alt="201-8">
</figure>
