---
title: "Zプローブの組み立て"
permalink: /make3d/assembling-the-z-probe/
toc: true
---
以下の部品を準備します。

- プリンターボディー
- マイクロスイッチ＆ケーブル
- プローブクリップ
- アルミ棒
- 安全ピン
- スプリング
- M2.5-8ボルト：２個
- M2.5-12ボルト：１個
- M2.5-20ボルト：１個
- M3ワッシャー(大)：１個

<figure>
  <img src="{{ '/assets/images/make3d/216/216-1.webp' | relative_url }}" alt="216-1">
</figure>

安全ピンの頭をカットします。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-2.webp' | relative_url }}" alt="216-2">
</figure>

安全ピンの針の部分を先端から約12mmのところでカットします。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-3.webp' | relative_url }}" alt="216-3">
</figure>

<figure>
  <img src="{{ '/assets/images/make3d/216/216-4.webp' | relative_url }}" alt="216-4">
</figure>

安全ピンの短い方をZプローブ左上の穴に奥まで差し込みます。安全ピンを下の方へ曲げます。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-5.webp' | relative_url }}" alt="216-5">
</figure>

<figure>
  <img src="{{ '/assets/images/make3d/216/216-6.webp' | relative_url }}" alt="216-6">
</figure>

一度安全ピンを取り外し、曲げた部分を直角にします。再度プローブの穴に挿入します。安全ピンの輪の部分にM2.5-8ボルトを通し、Zプローブに締め付けます。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-7.webp' | relative_url }}" alt="216-7">
</figure>

<figure>
  <img src="{{ '/assets/images/make3d/216/216-8.webp' | relative_url }}" alt="216-8">
</figure>

下の写真の様に、マイクロスイッチを取り付けます。向かって左側はM2.5-12ボルト、右側はM2.5-8ボルトを挿入します。

（注：右側のボルトは奥まで入りません。また回しても締まらない場合がありますが、左側のボルトがしっかり締まっていれば問題ありません。）

<figure>
  <img src="{{ '/assets/images/make3d/216/216-9.webp' | relative_url }}" alt="216-9">
</figure>

アルミ棒の先端から約75mmのところに印を付け、直角に折り曲げます。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-10.webp' | relative_url }}" alt="216-10">
</figure>

<figure>
  <img src="{{ '/assets/images/make3d/216/216-11.webp' | relative_url }}" alt="216-11">
</figure>

アルミ棒の短辺は約20mmの長さでニッパーを使って切断します。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-12.webp' | relative_url }}" alt="216-12">
</figure>

アルミ棒の短辺の内側をヤスリを使って若干平らな面を作ります。これはZプローブに引っかかり易くするためです。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-13.webp' | relative_url }}" alt="216-13">
</figure>

アルミ棒をZプローブの穴に挿入します。指で押さえるとマイクロスイッチのスイッチがカチッと入る事を確認します。また手を放した時、アルミ棒L字長辺の先端が、ホットエンドのノズル先端よりも下にある事を確認します。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-14.webp' | relative_url }}" alt="216-14">
</figure>

次に、アルミ棒を引き上げ、Zプローブのストッパー部にアルミ棒のL字短辺を引っ掛けます。この時、アルミ棒L字長辺の先端が、ホットエンドのノズル先端よりも上にある事を確認します。下になっている場合、ニッパーでアルミ棒の先端をカットして調整します。少しずつ調整し、上の写真の時はノズル先端よりも下、下の写真の時はノズルより上になるようにします。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-15.webp' | relative_url }}" alt="216-15">
</figure>

アルミ棒を一度Zプローブから外し、アルミ棒L字長辺の先端をヤスリで尖らせます（鋭角にする必要はありません）。終わったら、再度Zプローブの穴に挿入します。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-16.webp' | relative_url }}" alt="216-16">
</figure>

M3ワッシャー(大)、スプリング、プローブクリップ、M2.5-20ボルトを準備します。プローブクリップの横穴にあらかじめM2.5-20ボルトを適度に挿入します。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-17.webp' | relative_url }}" alt="216-17">
</figure>

上の写真の上から順番にアルミ棒の下から通していきます。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-18.webp' | relative_url }}" alt="216-18">
</figure>

<figure>
  <img src="{{ '/assets/images/make3d/216/216-19.webp' | relative_url }}" alt="216-19">
</figure>

プローブクリップのボルトの締める位置を決めます。プローブクリップを若干押し上げながらプローブクリップが下がらないように下側のアルミ棒を指でしっかりと押さえます。この状態でアルミ棒を指で押し上げます。スプリングがめいいっぱい縮んだ状態の時に、アルミ棒L字短辺がZプローブのストッパーより若干上側にくるよう、指でアルミ棒を押さえる位置を調整します。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-20.webp' | relative_url }}" alt="216-20">
</figure>

位置が決まったら、アルミ棒L字短辺の向きとボルトの向きを合わせてボルトを締めます。手を話すと、スプリングの力でマイクロスイッチのスイッチが押されている状態になることを確認します。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-21.webp' | relative_url }}" alt="216-21">
</figure>

<figure>
  <img src="{{ '/assets/images/make3d/216/216-22.webp' | relative_url }}" alt="216-22">
</figure>

次に、安全ピンの調整を行います。ピンセットの平らな面などでアルミ棒の先端を押し上げると、安全ピンによってZプローブのストッパー部へ収まるようにします。安全ピンの傾きを変えたり曲げたりして調整します。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-23.webp' | relative_url }}" alt="216-23">
</figure>

これがベストというやり方はないですが、こちらで試したところでは下の写真のような形状が比較的安定してストッパーに収まっているようでした。アルミ棒がスムーズに上下できないと安定しない場合があるので、Zプローブのアルミ棒が通る穴をヤスリで削ってみたり、この穴にシリコン系潤滑油を吹きかけたりしてみてもよいと思います。

最後に、アルミ棒L字短辺を適度な長さにカットします。あまり長い場合はロッドに接触する場合があるためです。

<figure>
  <img src="{{ '/assets/images/make3d/216/216-24.webp' | relative_url }}" alt="216-24">
</figure>

<figure>
  <img src="{{ '/assets/images/make3d/216/216-25.webp' | relative_url }}" alt="216-25">
</figure>
